### ISSUE TITLE
this is dumb

### ISSUE THREAD

**Issue by cymcymcymcym** [genius-harry/MusicGeneration#1]
dumb

**Comment by genius-harry** [comment]
no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not no it is not

**Comment by cymcymcymcym** [comment]
mark xu mark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xumark xu

**Comment by genius-harry** [comment]
![image](https://github.com/user-attachments/assets/68e03082-4947-4474-95ad-8c4b48bbaf6c)

**Comment by cymcymcymcym** [comment]
![4a012da8b3ea81731de798977af8246](https://github.com/user-attachments/assets/9560add1-bced-4180-b322-9f1940a237cb)
